// GlutenGo — datos de establecimientos v0.5
// Coordenadas para Leaflet (OpenStreetMap)
const lugares = [
  // ─── 100% SIN GLUTEN ───────────────────────────────────────────────────
  {
    slug: "la-panaderia-de-ramona",
    name: "La Panadería de Ramona",
    category: "panaderia",
    tipo: "exclusivo",
    address: "San José 894",
    neighborhood: "Centro",
    phone: "+598 2902 5555",
    desc: "Panadería 100% libre de gluten con panes artesanales, facturas y pastelería. Sin contaminación cruzada, todo bajo el mismo techo libre de gluten.",
    hours: { lun_vie: "8:00–20:00", sab: "9:00–14:00", dom: "Cerrado" },
    lat: -34.9047,
    lng: -56.1893,
    instagram: "@lapanaderiaderamona",
  },
  {
    slug: "cafe-ramona-centro",
    name: "Café Ramona (Centro)",
    category: "cafeteria",
    tipo: "exclusivo",
    address: "San José 900",
    neighborhood: "Centro",
    phone: "+598 2902 5555",
    desc: "Café y espacio 100% libre de gluten. Desayunos, almuerzos livianos, postres. Hermano de La Panadería de Ramona.",
    hours: { lun_vie: "8:30–19:00", sab: "9:00–15:00", dom: "Cerrado" },
    lat: -34.9048,
    lng: -56.1895,
    instagram: "@caferamona",
  },
  {
    slug: "cafe-ramona-wtc",
    name: "Café Ramona (WTC)",
    category: "cafeteria",
    tipo: "exclusivo",
    address: "Luis A. de Herrera 1196",
    neighborhood: "Buceo",
    phone: "+598 2628 0000",
    desc: "Sucursal del Café Ramona en el World Trade Center. 100% libre de gluten, ideal para almuerzos de trabajo.",
    hours: { lun_vie: "8:00–18:00", sab: "Cerrado", dom: "Cerrado" },
    lat: -34.9014,
    lng: -56.1504,
    instagram: "@caferamona",
  },
  {
    slug: "gluteno",
    name: "Gluteno",
    category: "restaurante",
    tipo: "exclusivo",
    address: "Scoseria 2637",
    neighborhood: "Punta Carretas",
    phone: "+598 2711 0000",
    desc: "Restaurante 100% libre de gluten con carta amplia: pasta, pizza, sándwiches. El nombre lo dice todo.",
    hours: { lun_vie: "12:00–22:00", sab: "12:00–23:00", dom: "12:00–21:00" },
    lat: -34.9190,
    lng: -56.1648,
    instagram: "@glutenouruguay",
  },
  {
    slug: "gout-gluten-free",
    name: "Gout Gluten Free",
    category: "cafeteria",
    tipo: "exclusivo",
    address: "Solano García 2496",
    neighborhood: "Punta Carretas",
    phone: "+598 2711 5555",
    desc: "Cafetería y pastelería completamente libre de gluten. Tortas, muffins, cookies y más sin riesgo de contaminación.",
    hours: { lun_sab: "9:00–20:00", dom: "10:00–16:00" },
    lat: -34.9215,
    lng: -56.1658,
    instagram: "@goutgf",
  },
  {
    slug: "mi-cocina-sin-gluten",
    name: "Mi Cocina Sin Gluten",
    category: "rotiseria",
    tipo: "exclusivo",
    address: "Solano García 2411",
    neighborhood: "Punta Carretas",
    phone: "+598 2710 0000",
    desc: "Rotisería y delivery 100% libre de gluten. Comida casera, viandas y platos listos. Gran opción para llevar.",
    hours: { lun_vie: "10:00–19:00", sab: "10:00–14:00", dom: "Cerrado" },
    lat: -34.9220,
    lng: -56.1649,
    instagram: "@micocinasgluten",
  },
  {
    slug: "nutriciencia",
    name: "Nutriciencia",
    category: "almacen",
    tipo: "exclusivo",
    address: "Gral. Urquiza 2828",
    neighborhood: "La Blanqueada",
    phone: "+598 2487 0000",
    desc: "Dietética y almacén 100% sin gluten. Productos importados, harinas alternativas, snacks y suplementos para celíacos.",
    hours: { lun_vie: "9:00–19:00", sab: "9:00–13:00", dom: "Cerrado" },
    lat: -34.8910,
    lng: -56.1510,
    instagram: "@nutricienciauruguay",
  },
  {
    slug: "recobeco",
    name: "RecoBeco",
    category: "cafeteria",
    tipo: "exclusivo",
    address: "Tacuarembó 1487",
    neighborhood: "Cordón",
    phone: "+598 2900 0000",
    desc: "Cafetería y espacio cultural 100% libre de gluten. Ambiente acogedor, brunch los fines de semana.",
    hours: { mar_dom: "9:00–21:00", lun: "Cerrado" },
    lat: -34.9028,
    lng: -56.1793,
    instagram: "@recobeco.uy",
  },
  {
    slug: "cocina-inclusiva",
    name: "Cocina Inclusiva",
    category: "restaurante",
    tipo: "exclusivo",
    address: "Colonia 1779",
    neighborhood: "Cordón",
    phone: "+598 2901 0000",
    desc: "Restaurante 100% libre de gluten con opciones también veganas. Almuerzo y cena, carta variada y precios accesibles.",
    hours: { lun_vie: "12:00–21:00", sab: "12:00–22:00", dom: "Cerrado" },
    lat: -34.9068,
    lng: -56.1748,
    instagram: "@cocinainclusiva",
  },

  // ─── MIXTOS CON OPCIONES SEGURAS ────────────────────────────────────────
  {
    slug: "la-commedia",
    name: "La Commedia",
    category: "restaurante",
    tipo: "mixto",
    address: "Viejo Pancho 2414",
    neighborhood: "Pocitos",
    phone: "+598 2709 0000",
    desc: "Restaurante italiano con sección de pasta sin gluten bien identificada. Informar al llegar para protocolo especial.",
    hours: { lun_dom: "12:00–23:00" },
    lat: -34.9146,
    lng: -56.1507,
    instagram: "@lacommediauruguay",
  },
  {
    slug: "almacen-de-pizzas",
    name: "Almacén de Pizzas",
    category: "restaurante",
    tipo: "mixto",
    address: "Av. Alfredo Arocena 1624",
    neighborhood: "Carrasco",
    phone: "+598 2601 0000",
    desc: "Pizzería con base para pizza sin gluten disponible. Siempre avisar al pedido; preparan en zona separada.",
    hours: { lun_dom: "19:00–23:30" },
    lat: -34.8995,
    lng: -56.0698,
    instagram: "@almacendepizzas",
  },
  {
    slug: "sano-deleite",
    name: "Sano Deleite",
    category: "cafeteria",
    tipo: "mixto",
    address: "18 de Julio 2344",
    neighborhood: "Cordón",
    phone: "+598 2408 0000",
    desc: "Cafetería healthy con varias opciones sin gluten marcadas en carta. Buen manejo de alérgenos.",
    hours: { lun_sab: "8:00–20:00", dom: "9:00–18:00" },
    lat: -34.9075,
    lng: -56.1655,
    instagram: "@sanodeleite",
  },
  {
    slug: "los-lenos",
    name: "Los Leños",
    category: "restaurante",
    tipo: "mixto",
    address: "San José 909",
    neighborhood: "Centro",
    phone: "+598 2902 0000",
    desc: "Parrilla tradicional con buenos cortes de carne. La proteína sola es naturalmente GF; cuidado con salsas y guarniciones.",
    hours: { lun_dom: "12:00–23:00" },
    lat: -34.9047,
    lng: -56.1897,
    instagram: "@losledosuruguay",
  },
  {
    slug: "la-lupita",
    name: "La Lupita",
    category: "restaurante",
    tipo: "mixto",
    address: "Luis de la Torre 565",
    neighborhood: "Pocitos",
    phone: "+598 2708 0000",
    desc: "Cocina mexicana con opciones sin gluten (tacos en hoja de lechuga, guacamole, carnes). Avisar siempre al mozo.",
    hours: { lun_dom: "12:00–23:00" },
    lat: -34.9168,
    lng: -56.1597,
    instagram: "@lalupitauy",
  },
  {
    slug: "tuit",
    name: "Tuit",
    category: "cafeteria",
    tipo: "mixto",
    address: "Ituzaingó 1434",
    neighborhood: "Ciudad Vieja",
    phone: "+598 2915 0000",
    desc: "Cafetería artesanal en Ciudad Vieja con varias tortas y sandwiches sin gluten identificados en pizarrón diario.",
    hours: { lun_vie: "9:00–19:00", sab: "10:00–16:00", dom: "Cerrado" },
    lat: -34.9061,
    lng: -56.2011,
    instagram: "@tuit.cafeteria",
  },
  {
    slug: "porto-vanilla",
    name: "Porto Vanilla",
    category: "cafeteria",
    tipo: "mixto",
    address: "Av. Alfredo Arocena 1558",
    neighborhood: "Carrasco",
    phone: "+598 2600 5555",
    desc: "Cafetería moderna en Carrasco con opciones SG bien señalizadas. Tortas de encargo sin gluten con 48h de anticipación.",
    hours: { lun_dom: "8:30–21:00" },
    lat: -34.8993,
    lng: -56.0703,
    instagram: "@portovarepas",
  },
  {
    slug: "bulebar",
    name: "Bulebar",
    category: "cafeteria",
    tipo: "mixto",
    address: "Williman 647",
    neighborhood: "Punta Carretas",
    phone: "+598 2712 0000",
    desc: "Cafetería de barrio con buena onda. Identifican opciones sin gluten en carta; preguntar sobre preparación.",
    hours: { lun_dom: "8:00–21:00" },
    lat: -34.9185,
    lng: -56.1636,
    instagram: "@bulebar.uy",
  },
  {
    slug: "cafetto-prado",
    name: "Cafetto Prado",
    category: "cafeteria",
    tipo: "mixto",
    address: "Joaquín Suárez 3640",
    neighborhood: "Prado",
    phone: "+598 2336 0000",
    desc: "Cafetería tranquila en el Prado con algunas opciones sin gluten. Ambiente familiar, buen café.",
    hours: { lun_vie: "9:00–19:00", sab: "9:00–14:00", dom: "Cerrado" },
    lat: -34.8735,
    lng: -56.1950,
    instagram: "@cafettoprado",
  },
  {
    slug: "la-otra",
    name: "La Otra",
    category: "restaurante",
    tipo: "mixto",
    address: "Tomás Diago 758",
    neighborhood: "Pocitos",
    phone: "+598 2710 5555",
    desc: "Bistró con carta flexible. Varios platos son naturalmente sin gluten; el equipo está capacitado.",
    hours: { mar_dom: "12:00–23:00", lun: "Cerrado" },
    lat: -34.9148,
    lng: -56.1556,
    instagram: "@laotra.bistro",
  },
  {
    slug: "locos-de-asar",
    name: "Locos de Asar",
    category: "restaurante",
    tipo: "mixto",
    address: "San José 1065",
    neighborhood: "Centro",
    phone: "+598 2901 5555",
    desc: "Parrilla con buena reputación en manejo de celíacos. Carnes y ensaladas sin gluten; avisar al reservar.",
    hours: { lun_dom: "12:00–23:30" },
    lat: -34.9062,
    lng: -56.1930,
    instagram: "@locosde_asar",
  },
  {
    slug: "las-delicias",
    name: "Las Delicias",
    category: "cafeteria",
    tipo: "mixto",
    address: "21 de Setiembre 2837",
    neighborhood: "Punta Carretas",
    phone: "+598 2711 7777",
    desc: "Pastelería con algunas opciones sin gluten marcadas. Mejor confirmar disponibilidad al llegar.",
    hours: { lun_dom: "9:00–21:00" },
    lat: -34.9202,
    lng: -56.1633,
    instagram: "@lasdelicias.uy",
  },
  {
    slug: "los-trovadores",
    name: "Los Trovadores",
    category: "restaurante",
    tipo: "mixto",
    address: "Gabriel Pereira 3202",
    neighborhood: "Pocitos",
    phone: "+598 2708 3333",
    desc: "Parrilla de barrio en Pocitos. Cortes de carne seguros, avisar sobre marinadas y salsas.",
    hours: { lun_dom: "12:00–23:00" },
    lat: -34.9097,
    lng: -56.1517,
    instagram: "@lostrovadores",
  },
  {
    slug: "artesania-pastelera",
    name: "Artesanía Pastelera",
    category: "panaderia",
    tipo: "mixto",
    address: "Av. Rivera 3431",
    neighborhood: "Pocitos",
    phone: "+598 2708 0000",
    desc: "Pastelería artesanal con pedidos personalizados sin gluten bajo encargo. Hablar con la dueña para coordinar.",
    hours: { mar_sab: "9:00–19:00", dom: "10:00–14:00", lun: "Cerrado" },
    lat: -34.9121,
    lng: -56.1522,
    instagram: "@artesaniapastelera",
  },

  