// GlutenGo — datos de establecimientos v0.5
// Coordenadas para Leaflet (OpenStreetMap)
var lugares = [
  // ─── 100% SIN GLUTEN ───────────────────────────────────────────────────
  {
    slug: "la-panaderia-de-ramona",
    name: "La Panadería de Ramona",
    category: "panaderia",
    tipo: "exclusivo",
    address: "San José 894",
    neighborhood: "Centro",
    phone: "+598 2902 5555",
    desc: "Panadería 100% libre de gluten con panes artesanales, facturas y pastelería. Sin contaminación cruzada, todo bajo el mismo techo libre de gluten.",
    hours: { lun_vie: "8:00–20:00", sab: "9:00–14:00", dom: "Cerrado" },
    lat: -34.9073,
    lng: -56.1972,
    instagram: "@lapanaderiaderamona",
  },
  {
    slug: "cafe-ramona-centro",
    name: "Café Ramona (Centro)",
    category: "cafeteria",
    tipo: "exclusivo",
    address: "San José 900",
    neighborhood: "Centro",
    phone: "+598 2902 5555",
    desc: "Café y espacio 100% libre de gluten. Desayunos, almuerzos livianos, postres. Hermano de La Panadería de Ramona.",
    hours: { lun_vie: "8:30–19:00", sab: "9:00–15:00", dom: "Cerrado" },
    lat: -34.9074,
    lng: -56.1972,
    instagram: "@caferamona",
  },
  {
    slug: "cafe-ramona-wtc",
    name: "Café Ramona (WTC)",
    category: "cafeteria",
    tipo: "exclusivo",
    address: "Luis A. de Herrera 1196",
    neighborhood: "Buceo",
    phone: "+598 2628 0000",
    desc: "Sucursal del Café Ramona en el World Trade Center. 100% libre de gluten, ideal para almuerzos de trabajo.",
    hours: { lun_vie: "8:00–18:00", sab: "Cerrado", dom: "Cerrado" },
    lat: -34.9059,
    lng: -56.1366,
    instagram: "@caferamona",
  },
  {
    slug: "gluteno",
    name: "Gluteno",
    category: "restaurante",
    tipo: "exclusivo",
    address: "Scoseria 2637",
    neighborhood: "Punta Carretas",
    phone: "+598 2711 0000",
    desc: "Restaurante 100% libre de gluten con carta amplia: pasta, pizza, sándwiches. El nombre lo dice todo.",
    hours: { lun_vie: "12:00–22:00", sab: "12:00–23:00", dom: "12:00–21:00" },
    lat: -34.9190,
    lng: -56.1648,
    instagram: "@glutenouruguay",
  },
  {
    slug: "gout-gluten-free",
    name: "Gout Gluten Free",
    category: "cafeteria",
    tipo: "exclusivo",
    address: "Solano García 2496",
    neighborhood: "Punta Carretas",
    phone: "+598 2711 5555",
    desc: "Cafetería y pastelería completamente libre de gluten. Tortas, muffins, cookies y más sin riesgo de contaminación.",
    hours: { lun_sab: "9:00–20:00", dom: "10:00–16:00" },
    lat: -34.9228,
    lng: -56.1595,
    instagram: "@goutgf",
  },
  {
    slug: "mi-cocina-sin-gluten",
    name: "Mi Cocina Sin Gluten",
    category: "rotiseria",
    tipo: "exclusivo",
    address: "Solano García 2411",
    neighborhood: "Punta Carretas",
    phone: "+598 2710 0000",
    desc: "Rotisería y delivery 100% libre de gluten. Comida casera, viandas y platos listos. Gran opción para llevar.",
    hours: { lun_vie: "10:00–19:00", sab: "10:00–14:00", dom: "Cerrado" },
    lat: -34.9220,
    lng: -56.1649,
    instagram: "@micocinasgluten",
  },
  {
    slug: "nutriciencia",
    name: "Nutriciencia",
    category: "almacen",
    tipo: "exclusivo",
    address: "Gral. Urquiza 2828",
    neighborhood: "La Blanqueada",
    phone: "+598 2487 0000",
    desc: "Dietética y almacén 100% sin gluten. Productos importados, harinas alternativas, snacks y suplementos para celíacos.",
    hours: { lun_vie: "9:00–19:00", sab: "9:00–13:00", dom: "Cerrado" },
    lat: -34.8910,
    lng: -56.1510,
    instagram: "@nutricienciauruguay",
  },
  {
    slug: "recobeco",
    name: "RecoBeco",
    category: "cafeteria",
    tipo: "exclusivo",
    address: "Tacuarembó 1487",
    neighborhood: "Cordón",
    phone: "+598 2900 0000",
    desc: "Cafetería y espacio cultural 100% libre de gluten. Ambiente acogedor, brunch los fines de semana.",
    hours: { mar_dom: "9:00–21:00", lun: "Cerrado" },
    lat: -34.9028,
    lng: -56.1793,
    instagram: "@recobeco.uy",
  },
  {
    slug: "cocina-inclusiva",
    name: "Cocina Inclusiva",
    category: "restaurante",
    tipo: "exclusivo",
    address: "Colonia 1779",
    neighborhood: "Cordón",
    phone: "+598 2901 0000",
    desc: "Restaurante 100% libre de gluten con opciones también veganas. Almuerzo y cena, carta variada y precios accesibles.",
    hours: { lun_vie: "12:00–21:00", sab: "12:00–22:00", dom: "Cerrado" },
    lat: -34.9068,
    lng: -56.1748,
    instagram: "@cocinainclusiva",
  },

  // ─── MIXTOS CON OPCIONES SEGURAS ────────────────────────────────────────
  {
    slug: "la-commedia",
    name: "La Commedia",
    category: "restaurante",
    tipo: "mixto",
    address: "Viejo Pancho 2414",
    neighborhood: "Pocitos",
    phone: "+598 2709 0000",
    desc: "Restaurante italiano con sección de pasta sin gluten bien identificada. Informar al llegar para protocolo especial.",
    hours: { lun_dom: "12:00–23:00" },
    lat: -34.9146,
    lng: -56.1507,
    instagram: "@lacommediauruguay",
  },
  {
    slug: "almacen-de-pizzas",
    name: "Almacén de Pizzas",
    category: "restaurante",
    tipo: "mixto",
    address: "Av. Alfredo Arocena 1624",
    neighborhood: "Carrasco",
    phone: "+598 2601 0000",
    desc: "Pizzería con base para pizza sin gluten disponible. Siempre avisar al pedido; preparan en zona separada.",
    hours: { lun_dom: "19:00–23:30" },
    lat: -34.8995,
    lng: -56.0698,
    instagram: "@almacendepizzas",
  },
  {
    slug: "sano-deleite",
    name: "Sano Deleite",
    category: "cafeteria",
    tipo: "mixto",
    address: "18 de Julio 2344",
    neighborhood: "Cordón",
    phone: "+598 2408 0000",
    desc: "Cafetería healthy con varias opciones sin gluten marcadas en carta. Buen manejo de alérgenos.",
    hours: { lun_sab: "8:00–20:00", dom: "9:00–18:00" },
    lat: -34.9075,
    lng: -56.1655,
    instagram: "@sanodeleite",
  },
  {
    slug: "los-lenos",
    name: "Los Leños",
    category: "restaurante",
    tipo: "mixto",
    address: "San José 909",
    neighborhood: "Centro",
    phone: "+598 2902 0000",
    desc: "Parrilla tradicional con buenos cortes de carne. La proteína sola es naturalmente GF; cuidado con salsas y guarniciones.",
    hours: { lun_dom: "12:00–23:00" },
    lat: -34.9047,
    lng: -56.1897,
    instagram: "@losledosuruguay",
  },
  {
    slug: "la-lupita",
    name: "La Lupita",
    category: "restaurante",
    tipo: "mixto",
    address: "Luis de la Torre 565",
    neighborhood: "Pocitos",
    phone: "+598 2708 0000",
    desc: "Cocina mexicana con opciones sin gluten (tacos en hoja de lechuga, guacamole, carnes). Avisar siempre al mozo.",
    hours: { lun_dom: "12:00–23:00" },
    lat: -34.9168,
    lng: -56.1597,
    instagram: "@lalupitauy",
  },
  {
    slug: "tuit",
    name: "Tuit",
    category: "cafeteria",
    tipo: "mixto",
    address: "Ituzaingó 1434",
    neighborhood: "Ciudad Vieja",
    phone: "+598 2915 0000",
    desc: "Cafetería artesanal en Ciudad Vieja con varias tortas y sandwiches sin gluten identificados en pizarrón diario.",
    hours: { lun_vie: "9:00–19:00", sab: "10:00–16:00", dom: "Cerrado" },
    lat: -34.9061,
    lng: -56.2011,
    instagram: "@tuit.cafeteria",
  },
  {
    slug: "porto-vanilla",
    name: "Porto Vanilla",
    category: "cafeteria",
    tipo: "mixto",
    address: "Av. Alfredo Arocena 1558",
    neighborhood: "Carrasco",
    phone: "+598 2600 5555",
    desc: "Cafetería moderna en Carrasco con opciones SG bien señalizadas. Tortas de encargo sin gluten con 48h de anticipación.",
    hours: { lun_dom: "8:30–21:00" },
    lat: -34.8993,
    lng: -56.0703,
    instagram: "@portovarepas",
  },
  {
    slug: "bulebar",
    name: "Bulebar",
    category: "cafeteria",
    tipo: "mixto",
    address: "Williman 647",
    neighborhood: "Punta Carretas",
    phone: "+598 2712 0000",
    desc: "Cafetería de barrio con buena onda. Identifican opciones sin gluten en carta; preguntar sobre preparación.",
    hours: { lun_dom: "8:00–21:00" },
    lat: -34.9185,
    lng: -56.1636,
    instagram: "@bulebar.uy",
  },
  {
    slug: "cafetto-prado",
    name: "Cafetto Prado",
    category: "cafeteria",
    tipo: "mixto",
    address: "Joaquín Suárez 3640",
    neighborhood: "Prado",
    phone: "+598 2336 0000",
    desc: "Cafetería tranquila en el Prado con algunas opciones sin gluten. Ambiente familiar, buen café.",
    hours: { lun_vie: "9:00–19:00", sab: "9:00–14:00", dom: "Cerrado" },
    lat: -34.8735,
    lng: -56.1950,
    instagram: "@cafettoprado",
  },
  {
    slug: "la-otra",
    name: "La Otra",
    category: "restaurante",
    tipo: "mixto",
    address: "Tomás Diago 758",
    neighborhood: "Pocitos",
    phone: "+598 2710 5555",
    desc: "Bistró con carta flexible. Varios platos son naturalmente sin gluten; el equipo está capacitado.",
    hours: { mar_dom: "12:00–23:00", lun: "Cerrado" },
    lat: -34.9148,
    lng: -56.1556,
    instagram: "@laotra.bistro",
  },
  {
    slug: "locos-de-asar",
    name: "Locos de Asar",
    category: "restaurante",
    tipo: "mixto",
    address: "San José 1065",
    neighborhood: "Centro",
    phone: "+598 2901 5555",
    desc: "Parrilla con buena reputación en manejo de celíacos. Carnes y ensaladas sin gluten; avisar al reservar.",
    hours: { lun_dom: "12:00–23:30" },
    lat: -34.9062,
    lng: -56.1930,
    instagram: "@locosde_asar",
  },
  {
    slug: "las-delicias",
    name: "Las Delicias",
    category: "cafeteria",
    tipo: "mixto",
    address: "21 de Setiembre 2837",
    neighborhood: "Punta Carretas",
    phone: "+598 2711 7777",
    desc: "Pastelería con algunas opciones sin gluten marcadas. Mejor confirmar disponibilidad al llegar.",
    hours: { lun_dom: "9:00–21:00" },
    lat: -34.9202,
    lng: -56.1633,
    instagram: "@lasdelicias.uy",
  },
  {
    slug: "los-trovadores",
    name: "Los Trovadores",
    category: "restaurante",
    tipo: "mixto",
    address: "Gabriel Pereira 3202",
    neighborhood: "Pocitos",
    phone: "+598 2708 3333",
    desc: "Parrilla de barrio en Pocitos. Cortes de carne seguros, avisar sobre marinadas y salsas.",
    hours: { lun_dom: "12:00–23:00" },
    lat: -34.9097,
    lng: -56.1517,
    instagram: "@lostrovadores",
  },
  {
    slug: "artesania-pastelera",
    name: "Artesanía Pastelera",
    category: "panaderia",
    tipo: "mixto",
    address: "Av. Rivera 3431",
    neighborhood: "Pocitos",
    phone: "+598 2708 0000",
    desc: "Pastelería artesanal con pedidos personalizados sin gluten bajo encargo. Hablar con la dueña para coordinar.",
    hours: { mar_sab: "9:00–19:00", dom: "10:00–14:00", lun: "Cerrado" },
    lat: -34.9121,
    lng: -56.1522,
    instagram: "@artesaniapastelera",
  },

  // ─── NUEVAS ALTAS Y SERVICIOS ONLINE ───────────────────────────────────
  {
    slug: "dalbertt",
    name: "Dalbertt",
    category: "cafeteria",
    tipo: "exclusivo",
    address: "Mercedes 791",
    neighborhood: "Ciudad Vieja",
    phone: "+598 96 018 784",
    desc: "Pastelería, brunch y cafetería con propuesta libre de gluten. Buena opción antes o después de pasar por el Auditorio del Sodre.",
    hours: { lun_dom: "Consultar horarios actuales" },
    lat: -34.9045,
    lng: -56.1996,
    instagram: "@dalbertt.uy",
  },
  {
    slug: "milena-gluten-free",
    name: "Milena Gluten Free",
    category: "cafeteria",
    tipo: "exclusivo",
    address: "Bvar. Artigas 2748 esq. Caraguatay",
    neighborhood: "Bella Vista",
    phone: "+598 91 628 458",
    desc: "Tienda y café 100% libre de gluten con desayunos, meriendas, productos para llevar y encargues dentro de Montevideo.",
    hours: { lun_sab: "9:00–21:00", dom: "Cerrado" },
    lat: -34.8718,
    lng: -56.1952,
    instagram: "@milena.glutenfree",
  },
  {
    slug: "bonus-gluten-free",
    name: "Bonus Gluten Free",
    category: "restaurante",
    tipo: "exclusivo",
    address: "Santiago de Chile 1015",
    neighborhood: "Palermo",
    phone: "",
    desc: "Hamburguesería y cafetería 100% gluten free en Palermo. También aparece para delivery online.",
    hours: { mie_dom: "Consultar horarios actuales" },
    lat: -34.9115,
    lng: -56.1849,
    instagram: "@bonusglutenfree",
  },
  {
    slug: "serendipia-gluten-free",
    name: "Serendipia Gluten Free",
    category: "panaderia",
    tipo: "exclusivo",
    address: "Pick up en Parque Batlle",
    neighborhood: "Parque Batlle",
    phone: "",
    desc: "Emprendimiento artesanal libre de gluten con pedidos por encargo y retiro en Parque Batlle.",
    hours: { lun_dom: "Pedidos con anticipación" },
    lat: -34.8940,
    lng: -56.1474,
    instagram: "@serendipia.glutenfree",
  },
  {
    slug: "delicias-con-vida",
    name: "Delicias con Vida",
    category: "cafeteria",
    tipo: "exclusivo",
    address: "Cordón",
    neighborhood: "Cordón",
    phone: "",
    desc: "Café y productos para llevar sin gluten. Recomendado para meriendas y encargues dentro de Montevideo.",
    hours: { lun_dom: "Consultar horarios actuales" },
    lat: -34.9009,
    lng: -56.1763,
    instagram: "@convida_singluten",
  },
  {
    slug: "la-molienda",
    name: "La Molienda",
    category: "almacen",
    tipo: "mixto",
    address: "Colonia 1870",
    neighborhood: "Cordón",
    phone: "+598 99 132 177",
    desc: "Almacén natural con filtro de productos aptos para celíacos y cafetería. Confirmar manipulación si vas a consumir en el local.",
    hours: { lun_vie: "8:30–21:00", sab: "9:00–17:00", dom: "Cerrado" },
    lat: -34.9009,
    lng: -56.1763,
    instagram: "@lamolienda.uy",
  },
  {
    slug: "de-la-casa-sin-gluten",
    name: "De La Casa Sin Gluten",
    category: "almacen",
    tipo: "exclusivo",
    address: "Paysandú y envíos a todo el país",
    neighborhood: "Online / Paysandú",
    phone: "+598 99 313 126",
    desc: "Elaboración de productos aptos para celíacos, venta a particulares y comercios, con envíos a distintos departamentos.",
    hours: { lun_dom: "Pedidos online" },
    lat: -32.3217,
    lng: -58.0892,
    instagram: "@delacasa_singluten",
  },
  {
    slug: "pura-delicias-sin-gluten",
    name: "PURA Delicias Sin Gluten",
    category: "panaderia",
    tipo: "exclusivo",
    address: "Maldonado y pedidos online",
    neighborhood: "Online / Maldonado",
    phone: "",
    desc: "Delicias artesanales sin gluten con catálogo online. Útil para encargues, regalos y stock dulce fuera de Montevideo.",
    hours: { lun_dom: "Pedidos online" },
    lat: -34.9087,
    lng: -54.9583,
    instagram: "@pura_deliciassingluten",
  },
  {
    slug: "pagana-pasteleria",
    name: "Pagana Pastelería",
    category: "cafeteria",
    tipo: "exclusivo",
    address: "Av. Giannattasio esq. Paul Harris",
    neighborhood: "Ciudad de la Costa",
    phone: "",
    desc: "Cafetería 100% libre de gluten en Solymar, con opciones dulces, saladas, veganas y sin azúcar.",
    hours: { mar_sab: "10:00–19:30", dom: "15:00–19:30", lun: "Cerrado" },
    lat: -34.8357,
    lng: -55.9655,
    instagram: "@paganaglutenfree",
  },
  {
    slug: "cblossom-sin-gluten",
    name: "Cblossom Sin Gluten",
    category: "cafeteria",
    tipo: "exclusivo",
    address: "Columbia Market, Av. Giannattasio",
    neighborhood: "Ciudad de la Costa",
    phone: "",
    desc: "Local sin gluten dentro de Columbia Market en Lagomar. Confirmar menú y horarios antes de ir.",
    hours: { lun_dom: "Consultar horarios actuales" },
    lat: -34.8352,
    lng: -55.9816,
    instagram: "@cblossomuru",
  },
  {
    slug: "il-forno-gf-lagomar",
    name: "Il Forno GF Lagomar",
    category: "restaurante",
    tipo: "exclusivo",
    address: "Columbia Market, Av. Giannattasio",
    neighborhood: "Ciudad de la Costa",
    phone: "",
    desc: "Pizzería gluten free en Columbia Market, con delivery disponible en apps. Confirmar horarios del local.",
    hours: { lun_dom: "Consultar horarios actuales" },
    lat: -34.8354,
    lng: -55.9818,
    instagram: "",
  },
  {
    slug: "rikuras-sin-gluten-el-pinar",
    name: "Rikuras Sin Gluten (El Pinar)",
    category: "restaurante",
    tipo: "exclusivo",
    address: "Pérez Butler esq. Santa Paula",
    neighborhood: "El Pinar",
    phone: "+598 95 710 000",
    desc: "Sucursal de cocina 100% sin gluten en El Pinar, enfocada en pizzas y platos para delivery o retiro.",
    hours: { lun_dom: "Consultar horarios actuales" },
    lat: -34.7938,
    lng: -55.9092,
    instagram: "@rikuras_singluten",
  },
  {
    slug: "rikuras-sin-gluten-malvin",
    name: "Rikuras Sin Gluten (Malvín)",
    category: "restaurante",
    tipo: "exclusivo",
    address: "Hipólito Yrigoyen 1728",
    neighborhood: "Malvín",
    phone: "+598 99 442 254",
    desc: "Cocina 100% sin gluten en Malvín, conocida por pizzas, delivery y opciones familiares.",
    hours: { mie_lun: "16:00–23:30", mar: "Cerrado" },
    lat: -34.8888,
    lng: -56.1096,
    instagram: "@rikuras_singluten",
  },
  {
    slug: "chocara",
    name: "ChocAra",
    category: "cafeteria",
    tipo: "exclusivo",
    address: "20 de Setiembre 1520",
    neighborhood: "Parque Batlle",
    phone: "+598 95 621 971",
    desc: "Restaurante y cafetería 100% sin gluten con opciones sin azúcar, sin lactosa, veganas y keto.",
    hours: { lun_vie: "7:30–20:00", sab: "11:00–20:00", dom: "Cerrado" },
    lat: -34.9004,
    lng: -56.1625,
    instagram: "@chocara.saboresqueunen",
  },
  {
    slug: "un-lugar-sin-gluten",
    name: "Un Lugar Sin Gluten",
    category: "rotiseria",
    tipo: "exclusivo",
    address: "Duvimioso Terra 2148 esq. Martín García",
    neighborhood: "La Comercial",
    phone: "",
    desc: "Takeaway y viandas 100% sin gluten con menú semanal, panificados y sector de almacén.",
    hours: { lun_vie: "10:00–19:00", sab: "10:00–15:00", dom: "Cerrado" },
    lat: -34.8872,
    lng: -56.1671,
    instagram: "@unlugarsingluten",
  },
  {
    slug: "zero-helados",
    name: "Zero Helados",
    category: "heladeria",
    tipo: "exclusivo",
    address: "26 de Marzo 1325",
    neighborhood: "Pocitos",
    phone: "",
    desc: "Heladería 100% sin gluten, con helados sin azúcar, sin lácteos, opciones veganas y cucuruchos aptos.",
    hours: { mar: "20:00–00:00", mie_vie: "17:00–00:00", sab: "12:00–00:00", dom: "12:00–22:00" },
    lat: -34.9082,
    lng: -56.1469,
    instagram: "@zerohelados",
  },
  {
    slug: "pecorino",
    name: "Pecorino",
    category: "restaurante",
    tipo: "exclusivo",
    address: "Bvar. España 2571",
    neighborhood: "Pocitos",
    phone: "",
    desc: "Local 100% sin gluten en Pocitos, con propuesta de cafetería, comidas y opciones para llevar.",
    hours: { lun_mie: "10:00–19:00", jue_sab: "16:00–23:00", dom: "Cerrado" },
    lat: -34.9123,
    lng: -56.1586,
    instagram: "@pecorino.uy",
  },
  {
    slug: "cocina-sabini",
    name: "Cocina Sabini Libre de Gluten",
    category: "almacen",
    tipo: "exclusivo",
    address: "Ruta Interbalnearia km 41.8",
    neighborhood: "Atlántida / Fortín de Santa Rosa",
    phone: "+598 98 643 181",
    desc: "Fábrica y tienda libre de gluten registrada, con pastas frescas congeladas, milanesas, empanadas y productos envasados.",
    hours: { lun_dom: "Consultar horarios actuales" },
    lat: -34.7699,
    lng: -55.8108,
    instagram: "",
  },
  {
    slug: "araza-parque-del-plata",
    name: "Arazá Tienda Natural",
    category: "almacen",
    tipo: "mixto",
    address: "Av. Mario Ferreira entre calles 9 y 10",
    neighborhood: "Parque del Plata",
    phone: "+598 99 980 372",
    desc: "Tienda natural con productos envasados para celíacos. Confirmar disponibilidad de marcas aptas antes de ir.",
    hours: { lun_dom: "Consultar horarios actuales" },
    lat: -34.7547,
    lng: -55.7052,
    instagram: "",
  },
  {
    slug: "calma-piriapolis",
    name: "Calma Piriápolis",
    category: "cafeteria",
    tipo: "exclusivo",
    address: "Atanasio Sierra 1069",
    neighborhood: "Piriápolis",
    phone: "",
    desc: "Café exclusivo sin gluten en Piriápolis, con meriendas, panes, tartas, alfajores y opciones saladas.",
    hours: { mie_lun: "16:00–20:00", mar: "Cerrado" },
    lat: -34.8655,
    lng: -55.2718,
    instagram: "",
  },
  {
    slug: "heladeria-angelote",
    name: "Heladería Angelote",
    category: "heladeria",
    tipo: "mixto",
    address: "Rambla de los Argentinos",
    neighborhood: "Piriápolis",
    phone: "",
    desc: "Heladería con cuidados para opciones sin gluten y cucuruchos aptos. Consultar protocolo al pedir.",
    hours: { lun_dom: "Consultar horarios actuales" },
    lat: -34.8583,
    lng: -55.2872,
    instagram: "",
  },
  {
    slug: "la-corniche-piriapolis",
    name: "La Corniche",
    category: "restaurante",
    tipo: "mixto",
    address: "Rambla de los Argentinos esq. Manuel Freire",
    neighborhood: "Piriápolis",
    phone: "",
    desc: "Restaurante con opciones sin gluten y panera apta según guías de viajeros. Confirmar protocolo en sala.",
    hours: { lun_dom: "Consultar horarios actuales" },
    lat: -34.8629,
    lng: -55.2739,
    instagram: "",
  },
  {
    slug: "lo-de-cecilia",
    name: "Lo de Cecilia",
    category: "cafeteria",
    tipo: "exclusivo",
    address: "Parada 18, Ruta 10",
    neighborhood: "Las Flores",
    phone: "",
    desc: "Casa de comidas 100% sin gluten en la costa de Maldonado, con desayunos, almuerzos y meriendas caseras.",
    hours: { lun_dom: "Consultar con anticipación" },
    lat: -34.8212,
    lng: -55.3256,
    instagram: "@lodececiliaok",
  },
  {
    slug: "exquisito-sin-gluten",
    name: "Exquisito Sin Gluten",
    category: "restaurante",
    tipo: "exclusivo",
    address: "Av. Roosevelt, parada 11",
    neighborhood: "Punta del Este",
    phone: "",
    desc: "Restaurante sin gluten en Punta del Este, recomendado por la comunidad para almuerzos, cenas y take away.",
    hours: { lun_dom: "Consultar horarios actuales" },
    lat: -34.9290,
    lng: -54.9345,
    instagram: "",
  },
  {
    slug: "namaste-rocha",
    name: "Namasté Tienda Natural",
    category: "almacen",
    tipo: "mixto",
    address: "Treinta y Tres 1965",
    neighborhood: "Rocha",
    phone: "",
    desc: "Tienda natural donde se consiguen productos sin gluten envasados y elaboraciones locales por encargo.",
    hours: { lun_dom: "Consultar horarios actuales" },
    lat: -34.4982,
    lng: -54.3247,
    instagram: "@namaste_rocha",
  },
  {
    slug: "simple-sin-tacc",
    name: "Simple Sin TACC",
    category: "panaderia",
    tipo: "exclusivo",
    address: "Rocha y La Paloma, por encargo",
    neighborhood: "Online / Rocha",
    phone: "",
    desc: "Emprendimiento dulce sin gluten por encargo, con reparto en Rocha y La Paloma.",
    hours: { lun_dom: "Pedidos online" },
    lat: -34.4982,
    lng: -54.3247,
    instagram: "@simplesintacc",
  },
  {
    slug: "la-casona-del-celiaco",
    name: "La Casona del Celíaco",
    category: "panaderia",
    tipo: "exclusivo",
    address: "Salto, pedidos y elaboración sin TACC",
    neighborhood: "Online / Salto",
    phone: "",
    desc: "Emprendimiento de Salto dedicado a panes, pastas, postres, tartas, tortas y pizzas sin TACC.",
    hours: { lun_dom: "Consultar pedidos" },
    lat: -31.3866,
    lng: -57.9738,
    instagram: "",
  },
];
